package com.easylearn;
// Generated Apr 30, 2017 7:38:54 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

/**
 * Employee2 generated by hbm2java
 */
public class Employee implements java.io.Serializable {

	private BigDecimal idEmp;
	private String nmFirst;
	private String nmLast;
	private String nmMid;
	private String txAddress;
	private Double amSalary;
	private Date dtJoin;

	public Employee() {
	}

	public Employee(BigDecimal idEmp) {
		this.idEmp = idEmp;
	}

	public Employee(BigDecimal idEmp, String nmFirst, String nmLast, String nmMid, String txAddress, Double amSalary,
			Date dtJoin) {
		this.idEmp = idEmp;
		this.nmFirst = nmFirst;
		this.nmLast = nmLast;
		this.nmMid = nmMid;
		this.txAddress = txAddress;
		this.amSalary = amSalary;
		this.dtJoin = dtJoin;
	}

	public BigDecimal getIdEmp() {
		return this.idEmp;
	}

	public void setIdEmp(BigDecimal idEmp) {
		this.idEmp = idEmp;
	}

	public String getNmFirst() {
		return this.nmFirst;
	}

	public void setNmFirst(String nmFirst) {
		this.nmFirst = nmFirst;
	}

	public String getNmLast() {
		return this.nmLast;
	}

	public void setNmLast(String nmLast) {
		this.nmLast = nmLast;
	}

	public String getNmMid() {
		return this.nmMid;
	}

	public void setNmMid(String nmMid) {
		this.nmMid = nmMid;
	}

	public String getTxAddress() {
		return this.txAddress;
	}

	public void setTxAddress(String txAddress) {
		this.txAddress = txAddress;
	}

	public Double getAmSalary() {
		return this.amSalary;
	}

	public void setAmSalary(Double amSalary) {
		this.amSalary = amSalary;
	}

	public Date getDtJoin() {
		return this.dtJoin;
	}

	public void setDtJoin(Date dtJoin) {
		this.dtJoin = dtJoin;
	}

}
