package com.easylearn;
// Generated Sep 29, 2016 11:21:05 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Cacheable;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.Cache;
import org.hibernate.annotations.CacheConcurrencyStrategy;

/**
 * Employee generated by hbm2java
 */
@Entity
@Table(name = "employee_temp", catalog = "java_weekend_batch1")
public class Employee implements java.io.Serializable {

	private int idEmp;
	private String nmFirst;
	private String nmLast;
	private String nmMid;
	private Date dtBirth;
	private String txAddress;
	private Double amSalary;
	private String dtName;

	public Employee() {
	}

	public Employee(int idEmp, String nmLast) {
		this.idEmp = idEmp;
		this.nmLast = nmLast;
	}

	public Employee(int idEmp, String nmFirst, String nmLast, String nmMid, Date dtBirth, String txAddress,
			Double amSalary, String dtName) {
		this.idEmp = idEmp;
		this.nmFirst = nmFirst;
		this.nmLast = nmLast;
		this.nmMid = nmMid;
		this.dtBirth = dtBirth;
		this.txAddress = txAddress;
		this.amSalary = amSalary;
		this.dtName = dtName;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "ID_EMP", unique = true, nullable = false)
	public int getIdEmp() {
		return this.idEmp;
	}

	public void setIdEmp(int idEmp) {
		this.idEmp = idEmp;
	}

	@Column(name = "NM_FIRST", length = 40)
	public String getNmFirst() {
		return this.nmFirst;
	}

	public void setNmFirst(String nmFirst) {
		this.nmFirst = nmFirst;
	}

	@Column(name = "NM_LAST", nullable = false, length = 40)
	public String getNmLast() {
		return this.nmLast;
	}

	public void setNmLast(String nmLast) {
		this.nmLast = nmLast;
	}

	@Column(name = "NM_MID", length = 15)
	public String getNmMid() {
		return this.nmMid;
	}

	public void setNmMid(String nmMid) {
		this.nmMid = nmMid;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DT_BIRTH", length = 0)
	public Date getDtBirth() {
		return this.dtBirth;
	}

	public void setDtBirth(Date dtBirth) {
		this.dtBirth = dtBirth;
	}

	@Column(name = "TX_ADDRESS", length = 264)
	public String getTxAddress() {
		return this.txAddress;
	}

	public void setTxAddress(String txAddress) {
		this.txAddress = txAddress;
	}

	@Column(name = "AM_SALARY", precision = 22, scale = 0)
	public Double getAmSalary() {
		return this.amSalary;
	}

	public void setAmSalary(Double amSalary) {
		this.amSalary = amSalary;
	}

	@Column(name = "DT_NAME", length = 50)
	public String getDtName() {
		return this.dtName;
	}

	public void setDtName(String dtName) {
		this.dtName = dtName;
	}

	@Override
	public String toString() {
		return "Employee [idEmp=" + idEmp + ", nmFirst=" + nmFirst + ", nmLast=" + nmLast + ", nmMid=" + nmMid
				+ ", dtBirth=" + dtBirth + ", txAddress=" + txAddress + ", amSalary=" + amSalary + ", dtName=" + dtName
				+ "]";
	}

}
