package com.easylearn;
// Generated Apr 30, 2017 5:58:16 PM by Hibernate Tools 3.4.0.CR1

/**
 * Employee generated by hbm2java
 */
public class Employee implements java.io.Serializable {

	private Integer idEmp;
	private String firstName;
	private String lastName;
	private String middleName;
	private String phoneNumber;
	private String emailId;
	private String txAddress;

	public Employee() {
	}

	public Employee(String firstName, String lastName, String middleName, String phoneNumber, String emailId,
			String txAddress) {
		this.firstName = firstName;
		this.lastName = lastName;
		this.middleName = middleName;
		this.phoneNumber = phoneNumber;
		this.emailId = emailId;
		this.txAddress = txAddress;
	}

	public Integer getIdEmp() {
		return this.idEmp;
	}

	public void setIdEmp(Integer idEmp) {
		this.idEmp = idEmp;
	}

	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	public String getMiddleName() {
		return this.middleName;
	}

	public void setMiddleName(String middleName) {
		this.middleName = middleName;
	}

	public String getPhoneNumber() {
		return this.phoneNumber;
	}

	public void setPhoneNumber(String phoneNumber) {
		this.phoneNumber = phoneNumber;
	}

	public String getEmailId() {
		return this.emailId;
	}

	public void setEmailId(String emailId) {
		this.emailId = emailId;
	}

	public String getTxAddress() {
		return this.txAddress;
	}

	public void setTxAddress(String txAddress) {
		this.txAddress = txAddress;
	}

	@Override
	public String toString() {
		return "Employee [idEmp=" + idEmp + ", firstName=" + firstName + ", lastName=" + lastName + ", middleName="
				+ middleName + ", phoneNumber=" + phoneNumber + ", emailId=" + emailId + ", txAddress=" + txAddress
				+ "]";
	}

}
