package com.easylean;

// default package
// Generated May 4, 2016 5:51:38 AM by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * Library generated by hbm2java
 */
@Entity
@Table(name = "1_LIBRARY", catalog = "java_weekend_batch1")
public class Library implements java.io.Serializable {

	private int idStuLibrary;
	private Student student;
	private String nmBook;
	private Date dtAlloted;
	private Date dtReturn;

	public Library() {
	}

	public Library(Student student) {
		this.student = student;
	}

	@Override
	public String toString() {
		return "Library [idStuLibrary=" + idStuLibrary + ", nmBook=" + nmBook + ", dtAlloted="
				+ dtAlloted + ", dtReturn=" + dtReturn + "]";
	}

	public Library(Student student, String nmBook, Date dtAlloted, Date dtReturn) {
		this.student = student;
		this.nmBook = nmBook;
		this.dtAlloted = dtAlloted;
		this.dtReturn = dtReturn;
	}

	@GenericGenerator(name = "generator", strategy = "foreign", parameters = @Parameter(name = "property", value = "student"))
	@Id
	@GeneratedValue(generator = "generator")
	@Column(name = "ID_STU_LIBRARY", unique = true, nullable = false)
	public int getIdStuLibrary() {
		return this.idStuLibrary;
	}

	public void setIdStuLibrary(int idStuLibrary) {
		this.idStuLibrary = idStuLibrary;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	public Student getStudent() {
		return this.student;
	}

	public void setStudent(Student student) {
		this.student = student;
	}

	@Column(name = "NM_BOOK", length = 50)
	public String getNmBook() {
		return this.nmBook;
	}

	public void setNmBook(String nmBook) {
		this.nmBook = nmBook;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DT_ALLOTED", length = 0)
	public Date getDtAlloted() {
		return this.dtAlloted;
	}

	public void setDtAlloted(Date dtAlloted) {
		this.dtAlloted = dtAlloted;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DT_RETURN", length = 0)
	public Date getDtReturn() {
		return this.dtReturn;
	}

	public void setDtReturn(Date dtReturn) {
		this.dtReturn = dtReturn;
	}

}
