package com.easylean;

// default package
// Generated May 4, 2016 5:51:38 AM by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Student generated by hbm2java
 */
@Entity
@Table(name = "1_STUDENT", catalog = "java_weekend_batch1")
public class Student implements java.io.Serializable {

	private Integer idStudent;
	private String nmStudent;
	private String txCourse;
	private String phNumber;
	private Date dtBirth;
	private String txAddress;
	private Library library;

	public Student() {
	}

	public Student(String nmStudent, Date dtBirth) {
		this.nmStudent = nmStudent;
		this.dtBirth = dtBirth;
	}

	@Override
	public String toString() {
		return "Student [idStudent=" + idStudent + ", nmStudent=" + nmStudent + ", txCourse=" + txCourse + ", phNumber="
				+ phNumber + ", dtBirth=" + dtBirth + ", txAddress=" + txAddress+"]";
	}

	public Student(String nmStudent, String txCourse, String phNumber, Date dtBirth, String txAddress,
			Library library) {
		this.nmStudent = nmStudent;
		this.txCourse = txCourse;
		this.phNumber = phNumber;
		this.dtBirth = dtBirth;
		this.txAddress = txAddress;
		this.library = library;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ID_STUDENT", unique = true, nullable = false)
	public Integer getIdStudent() {
		return this.idStudent;
	}

	public void setIdStudent(Integer idStudent) {
		this.idStudent = idStudent;
	}

	@Column(name = "NM_STUDENT", nullable = false, length = 60)
	public String getNmStudent() {
		return this.nmStudent;
	}

	public void setNmStudent(String nmStudent) {
		this.nmStudent = nmStudent;
	}

	@Column(name = "TX_COURSE", length = 30)
	public String getTxCourse() {
		return this.txCourse;
	}

	public void setTxCourse(String txCourse) {
		this.txCourse = txCourse;
	}

	@Column(name = "PH_NUMBER", length = 15)
	public String getPhNumber() {
		return this.phNumber;
	}

	public void setPhNumber(String phNumber) {
		this.phNumber = phNumber;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DT_BIRTH", nullable = false, length = 0)
	public Date getDtBirth() {
		return this.dtBirth;
	}

	public void setDtBirth(Date dtBirth) {
		this.dtBirth = dtBirth;
	}

	@Column(name = "TX_ADDRESS", length = 80)
	public String getTxAddress() {
		return this.txAddress;
	}

	public void setTxAddress(String txAddress) {
		this.txAddress = txAddress;
	}

	@OneToOne(fetch = FetchType.LAZY, mappedBy = "student")
	public Library getLibrary() {
		return this.library;
	}

	public void setLibrary(Library library) {
		this.library = library;
	}

}
