
package com.easylearn;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "WelcomeMessage", targetNamespace = "http://easylearn.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WelcomeMessage {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "wishUser", targetNamespace = "http://easylearn.com/", className = "com.easylearn.WishUser")
    @ResponseWrapper(localName = "wishUserResponse", targetNamespace = "http://easylearn.com/", className = "com.easylearn.WishUserResponse")
    @Action(input = "http://easylearn.com/WelcomeMessage/wishUserRequest", output = "http://easylearn.com/WelcomeMessage/wishUserResponse")
    public String wishUser(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
