
package com.easylearn;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "WelcomeMessageService", targetNamespace = "http://easylearn.com/", wsdlLocation = "http://localhost:8088/SOAP_JAXWS_ServiceProject/WelcomeMessageService?wsdl")
public class WelcomeMessageService
    extends Service
{

    private final static URL WELCOMEMESSAGESERVICE_WSDL_LOCATION;
    private final static WebServiceException WELCOMEMESSAGESERVICE_EXCEPTION;
    private final static QName WELCOMEMESSAGESERVICE_QNAME = new QName("http://easylearn.com/", "WelcomeMessageService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://laptop-dfmdv5fg:5678/SOAP_JAXWS_ServiceProject/WelcomeMessageService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        WELCOMEMESSAGESERVICE_WSDL_LOCATION = url;
        WELCOMEMESSAGESERVICE_EXCEPTION = e;
    }

    public WelcomeMessageService() {
        super(__getWsdlLocation(), WELCOMEMESSAGESERVICE_QNAME);
    }

    public WelcomeMessageService(WebServiceFeature... features) {
        super(__getWsdlLocation(), WELCOMEMESSAGESERVICE_QNAME, features);
    }

    public WelcomeMessageService(URL wsdlLocation) {
        super(wsdlLocation, WELCOMEMESSAGESERVICE_QNAME);
    }

    public WelcomeMessageService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, WELCOMEMESSAGESERVICE_QNAME, features);
    }

    public WelcomeMessageService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WelcomeMessageService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns WelcomeMessage
     */
    @WebEndpoint(name = "WelcomeMessagePort")
    public WelcomeMessage getWelcomeMessagePort() {
        return super.getPort(new QName("http://easylearn.com/", "WelcomeMessagePort"), WelcomeMessage.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WelcomeMessage
     */
    @WebEndpoint(name = "WelcomeMessagePort")
    public WelcomeMessage getWelcomeMessagePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://easylearn.com/", "WelcomeMessagePort"), WelcomeMessage.class, features);
    }

    private static URL __getWsdlLocation() {
        if (WELCOMEMESSAGESERVICE_EXCEPTION!= null) {
            throw WELCOMEMESSAGESERVICE_EXCEPTION;
        }
        return WELCOMEMESSAGESERVICE_WSDL_LOCATION;
    }

}
