package com.easylearn;
// Generated May 5, 2016 5:24:37 AM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * PhoneNumbers generated by hbm2java
 */
@Entity
@Table(name = "phone_numbers", catalog = "springhbdb")
public class PhoneNumbers implements java.io.Serializable {

	private int phone;
	private Users users;
	private String numberType;

	public PhoneNumbers() {
	}

	public PhoneNumbers(int phone) {
		this.phone = phone;
	}

	public PhoneNumbers(int phone, Users users, String numberType) {
		this.phone = phone;
		this.users = users;
		this.numberType = numberType;
	}

	@Id

	@Column(name = "PHONE", unique = true, nullable = false)
	public int getPhone() {
		return this.phone;
	}

	public void setPhone(int phone) {
		this.phone = phone;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "UNID")
	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

	@Column(name = "NUMBER_TYPE", length = 20)
	public String getNumberType() {
		return this.numberType;
	}

	public void setNumberType(String numberType) {
		this.numberType = numberType;
	}

}
