package com.easylearn;
// Generated May 6, 2016 4:51:49 AM by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * Employeee generated by hbm2java
 */
@Entity
@Table(name = "5_EMPLOYEE", catalog = "java_weekend_batch1")
@PrimaryKeyJoinColumn(name="person_id")
public class Employeee extends Person {

	private Date joiningDate;
	private String departmentName;

	public Employeee() {
	}

	public Employeee(String firstname, String lastname, String departmentName,Date joiningDate) {
		super(firstname, lastname);
		this.joiningDate = joiningDate;
		this.departmentName = departmentName;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "joining_date", length = 0)
	public Date getJoiningDate() {
		return this.joiningDate;
	}

	public void setJoiningDate(Date joiningDate) {
		this.joiningDate = joiningDate;
	}

	@Column(name = "department_name", length = 50)
	public String getDepartmentName() {
		return this.departmentName;
	}

	public void setDepartmentName(String departmentName) {
		this.departmentName = departmentName;
	}

}
