package com.easylearn;
// Generated May 6, 2016 4:51:49 AM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * Owner generated by hbm2java
 */
@Entity
@Table(name = "5_OWNER", catalog = "java_weekend_batch1")
@PrimaryKeyJoinColumn(name = "person_id")
public class Owner extends Person {

	private Long stocks;
	private Long partnershipStake;

	public Owner() {
	}

	public Owner(String firstname, String lastname, Long stocks, Long partnershipStake) {
		super(firstname, lastname);
		this.stocks = stocks;
		this.partnershipStake = partnershipStake;
	}

	@Column(name = "stocks")
	public Long getStocks() {
		return this.stocks;
	}

	public void setStocks(Long stocks) {
		this.stocks = stocks;
	}

	@Column(name = "partnership_stake")
	public Long getPartnershipStake() {
		return this.partnershipStake;
	}

	public void setPartnershipStake(Long partnershipStake) {
		this.partnershipStake = partnershipStake;
	}

}
