package com.easylearn;
// Generated May 6, 2016 4:51:49 AM by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * Employeee generated by hbm2java
 */
@Entity
@Table(name = "5_STUDENT", catalog = "java_weekend_batch1")
@PrimaryKeyJoinColumn(name="person_id")
public class Student extends Person {

	private Date admissionDate;
	private String course;

	public Student() {
	}

	public Student(String firstname, String lastname, String course, Date admissionDate) {
		super(firstname, lastname);
		this.admissionDate = admissionDate;
		this.course = course;
	}

	@Temporal(TemporalType.DATE)
	@Column(name="ADMSSION_DATE")
	public Date getAdmissionDate() {
		return admissionDate;
	}

	public void setAdmissionDate(Date admissionDate) {
		this.admissionDate = admissionDate;
	}

	@Column(name="NM_COUSE", length = 30)
	public String getCourse() {
		return course;
	}

	public void setCourse(String course) {
		this.course = course;
	}

}
