package com.easylearn;
// Generated May 6, 2017 8:24:28 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Department generated by hbm2java
 */
@Entity
@Table(name = "department", catalog = "java_weekend_batch1")
public class Department implements java.io.Serializable {

	private int idDept;
	private String dtName;
	private Integer noOfEmployees;
	private String hdDept;
	private Set<Employee> employees = new HashSet<Employee>(0);

	public Department() {
	}

	public Department(int idDept) {
		this.idDept = idDept;
	}

	@Override
	public String toString() {
		return "Department [idDept=" + idDept + ", dtName=" + dtName + ", noOfEmployees=" + noOfEmployees + ", hdDept="
				+ hdDept + "]";
	}

	public Department(int idDept, String dtName, Integer noOfEmployees, String hdDept, Set<Employee> employees) {
		this.idDept = idDept;
		this.dtName = dtName;
		this.noOfEmployees = noOfEmployees;
		this.hdDept = hdDept;
		this.employees = employees;
	}

	@Id

	@Column(name = "ID_DEPT", unique = true, nullable = false)
	public int getIdDept() {
		return this.idDept;
	}

	public void setIdDept(int idDept) {
		this.idDept = idDept;
	}

	@Column(name = "DT_NAME", length = 40)
	public String getDtName() {
		return this.dtName;
	}

	public void setDtName(String dtName) {
		this.dtName = dtName;
	}

	@Column(name = "NO_OF_EMPLOYEES")
	public Integer getNoOfEmployees() {
		return this.noOfEmployees;
	}

	public void setNoOfEmployees(Integer noOfEmployees) {
		this.noOfEmployees = noOfEmployees;
	}

	@Column(name = "HD_DEPT", length = 60)
	public String getHdDept() {
		return this.hdDept;
	}

	public void setHdDept(String hdDept) {
		this.hdDept = hdDept;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "department")
	public Set<Employee> getEmployees() {
		return this.employees;
	}

	public void setEmployees(Set<Employee> employees) {
		this.employees = employees;
	}

}
