package com.easylearn;
// Generated May 5, 2016 6:27:00 AM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Table;

/**
 * Projects generated by hbm2java
 */
@Entity
@Table(name = "3_PROJECTS", catalog = "java_weekend_batch1")
public class Projects implements java.io.Serializable {

	private int proid;
	private String proname;
	private Set<Programmers> programmerses = new HashSet<Programmers>(0);

	public Projects() {
	}

	public Projects(int proid) {
		this.proid = proid;
	}

	public Projects(int proid, String proname) {
		this.proid = proid;
		this.proname = proname;
		this.programmerses = programmerses;
	}

	@Id

	@Column(name = "proid", unique = true, nullable = false)
	public int getProid() {
		return this.proid;
	}

	public void setProid(int proid) {
		this.proid = proid;
	}

	@Column(name = "proname", length = 60)
	public String getProname() {
		return this.proname;
	}

	public void setProname(String proname) {
		this.proname = proname;
	}

	@ManyToMany(fetch = FetchType.LAZY,cascade=CascadeType.ALL)
	@JoinTable(name = "3_PROGRAMMERS_PROJECTS", catalog = "java_weekend_batch1", 
		joinColumns = {
				@JoinColumn(name = "project_id", nullable = false, updatable = false) }, 
		inverseJoinColumns = {
				@JoinColumn(name = "programmer_id", nullable = false, updatable = false) 
				}
			)
	public Set<Programmers> getProgrammerses() {
		return this.programmerses;
	}

	public void setProgrammerses(Set<Programmers> programmerses) {
		this.programmerses = programmerses;
	}

}
