package com.easylearn;
// Generated Apr 30, 2017 8:22:05 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Employee generated by hbm2java
 */
@Entity
@Table(name = "employee", catalog = "java_weekend_batch1")
public class Employee implements java.io.Serializable {

	private Integer idEmp;
	private String firstName;
	private String lastName;
	private String middleName;
	private String phoneNumber;
	private String emailId;
	private String txAddress;

	public Employee() {
	}

	public Employee(String firstName, String lastName, String middleName, String phoneNumber, String emailId,
			String txAddress) {
		this.firstName = firstName;
		this.lastName = lastName;
		this.middleName = middleName;
		this.phoneNumber = phoneNumber;
		this.emailId = emailId;
		this.txAddress = txAddress;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ID_EMP", unique = true, nullable = false)
	public Integer getIdEmp() {
		return this.idEmp;
	}

	public void setIdEmp(Integer idEmp) {
		this.idEmp = idEmp;
	}

	@Column(name = "FIRST_NAME", length = 40)
	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	@Column(name = "LAST_NAME", length = 40)
	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	@Column(name = "MIDDLE_NAME", length = 30)
	public String getMiddleName() {
		return this.middleName;
	}

	public void setMiddleName(String middleName) {
		this.middleName = middleName;
	}

	@Column(name = "PHONE_NUMBER", length = 10)
	public String getPhoneNumber() {
		return this.phoneNumber;
	}

	public void setPhoneNumber(String phoneNumber) {
		this.phoneNumber = phoneNumber;
	}

	@Column(name = "EMAIL_ID", length = 265)
	public String getEmailId() {
		return this.emailId;
	}

	public void setEmailId(String emailId) {
		this.emailId = emailId;
	}

	@Column(name = "TX_ADDRESS", length = 268)
	public String getTxAddress() {
		return this.txAddress;
	}

	public void setTxAddress(String txAddress) {
		this.txAddress = txAddress;
	}

	@Override
	public String toString() {
		return "Employee [idEmp=" + idEmp + ", firstName=" + firstName + ", lastName=" + lastName + ", middleName="
				+ middleName + ", phoneNumber=" + phoneNumber + ", emailId=" + emailId + ", txAddress=" + txAddress
				+ "]";
	}

}
